// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_tykgateway

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func TykgatewayProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.StringAttribute{
				Required:            true,
				Description:         "The API key for authenticating with the Tyk Gateway.",
				MarkdownDescription: "The API key for authenticating with the Tyk Gateway.",
			},
			"gateway_url": schema.StringAttribute{
				Required:            true,
				Description:         "The URL of the Tyk Gateway instance.",
				MarkdownDescription: "The URL of the Tyk Gateway instance.",
			},
		},
	}
}

type TykgatewayModel struct {
	ApiKey     types.String `tfsdk:"api_key"`
	GatewayUrl types.String `tfsdk:"gateway_url"`
}
