// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_tykgateway_key

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TykgatewayKeyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"expires_at": schema.StringAttribute{
				Optional:            true,
				Description:         "The expiration date of the API key in ISO 8601 format.",
				MarkdownDescription: "The expiration date of the API key in ISO 8601 format.",
			},
			"key_name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the API key.",
				MarkdownDescription: "The name of the API key.",
			},
			"key_value": schema.StringAttribute{
				Required:            true,
				Description:         "The value of the API key.",
				MarkdownDescription: "The value of the API key.",
			},
		},
	}
}

type TykgatewayKeyModel struct {
	ExpiresAt types.String `tfsdk:"expires_at"`
	KeyName   types.String `tfsdk:"key_name"`
	KeyValue  types.String `tfsdk:"key_value"`
}
